"""Initial table

Revision ID: 249d77c3f559
Revises: 
Create Date: 2025-09-07 12:27:43.137702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249d77c3f559'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_age', sa.Integer(), nullable=True),
    sa.Column('person_income', sa.Integer(), nullable=True),
    sa.Column('person_home_ownership', sa.String(), nullable=True),
    sa.Column('person_emp_length', sa.Float(), nullable=True),
    sa.Column('loan_intent', sa.String(), nullable=True),
    sa.Column('loan_grade', sa.String(), nullable=True),
    sa.Column('loan_amnt', sa.Integer(), nullable=True),
    sa.Column('loan_int_rate', sa.Float(), nullable=True),
    sa.Column('loan_percent_income', sa.Float(), nullable=True),
    sa.Column('cb_person_default_on_file', sa.String(), nullable=True),
    sa.Column('cb_person_cred_hist_length', sa.Integer(), nullable=True),
    sa.Column('predicted_status', sa.Integer(), nullable=True),
    sa.Column('actual_status', sa.Integer(), nullable=True),
    sa.Column('probability_repaid', sa.Float(), nullable=True),
    sa.Column('probability_default', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_id'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
